packages:
  - packages/**
  - examples/**

allowBuilds:
  "@swc/core": true
  esbuild: true

catalog:
  "@types/node": "^25.7.0"
  tsdown: "^0.22.0"

engineStrict: true
strictPeerDependencies: true
shellEmulator: true
preferWorkspacePackages: true
linkWorkspacePackages: true
enablePrePostScripts: true
